### ISSUE TITLE
Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'WorkshopManagementEventStore'. [CLIENT: 172.18.0.14]

### ISSUE THREAD

**Issue by wensan312** [EdwinVW/pitstop#23] opened 2019-01-17 03:19 UTC
Hi,thanks for this awesome project. I am new to all this microservices, docker and rabbitmq. Was thinking to use your youtube and this project as a startup for me to learn.

I followed your "Readme" section "Starting the application", and doing the docker-compose up. However I have issue on the error below.

2019-01-17 03:11:42.98 Logon       Error: 18456, Severity: 14, State: 38.
2019-01-17 03:11:42.98 Logon       Login failed for user 'sa'. Reason: Failed to open the explicitly specified database 'WorkshopManagementEventStore'. [CLIENT: 172.18.0.14]

The error logs like the login username/password failed for sa. But I have no idea how to SQL Server and check it. You mentioned:

> The first time the services are started, the necessary databases are automatically created. You could check this by connecting to the SQL Server using SSMS (server localhost, port 1434; separate the server and port with a comma in SSMS: localhost,1434) ...........

I know that, sql server is now inside the docker container, and how should I access to it? By using my host sql server management studio and login to localhost,1434? Or?

Sorry to bother you, thanks a lot for helping.

**Comment by EdwinVW** [comment] 2019-01-17 03:41
Hi @wensan312, thanks for your interest in this project. I hope you can learn something from studying it!

Regarding your question: yes, you can just use SQL Server Management Studio on your host and connect to `localhost,1434`, username `sa` and password `8jkGh47hnDw89Haq8LN2`.

With regards to the error: I haven't seen this error before. So in order to solve this, could you answer the following questions:

- Are any of the other databases created (you can check using SSMS as described above)?
- Does the error persist if you shutdown and restart the solution again?
- Have you followed the instructions in the README on changing the default memory settings for Docker desktop?
- What version of the SQL Server for Linux are you using? If you share the output of the command `docker inspect microsoft/mssql-server-linux`, I can check the version.

Please provide answers to these questions so we can start troubleshooting and try to find the root-cause of this issue.

**Comment by wensan312** [comment] 2019-01-17 07:11
1) I can login using SSMS with the port given. I see these database: CustomerManagement, Invoicing, Notification, VehicleManagement, WorkshopManagement.

2) Error persist.

3) I installed Docker Desktop, with Kitematic. I can see a list of containers at left, and when I go for Settings, Advanced, I didn't see anything to adjust the CPU/Memory.
![image](https://user-images.githubusercontent.com/46769661/51301427-1b657400-1a6a-11e9-8009-2860eab14691.png)
![image](https://user-images.githubusercontent.com/46769661/51301434-25877280-1a6a-11e9-8259-3de945638444.png)


4) The output of the file:
[
    {
        "Id": "sha256:314918ddaedfedc0345d3191546d800bd7f28bae180541c9b8b45776d322c8c2",
        "RepoTags": [
            "microsoft/mssql-server-linux:latest"
        ],
        "RepoDigests": [
            "microsoft/mssql-server-linux@sha256:9b700672670bb3db4b212e8aef841ca79eb2fce7d5975a5ce35b7129a9b90ec0"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2018-12-17T19:37:22.052136555Z",
        "Container": "ad4994d21cb3a364fcac4e419fd5827e1723c86e767a321876c49f8f75c7d132",
        "ContainerConfig": {
            "Hostname": "4dcf0239b565",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/opt/mssql/bin/sqlservr\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:becb2cc726794b29b88a3a2a82cf524080b551b81b67f143fefc2970310fb6c8",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "com.microsoft.product": "Microsoft SQL Server",
                "com.microsoft.version": "14.0.3048.4",
                "vendor": "Microsoft"
            }
        },
        "DockerVersion": "1.13.0",
        "Author": "dpgswdist@microsoft.com",
        "Config": {
            "Hostname": "4dcf0239b565",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/opt/mssql/bin/sqlservr"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:becb2cc726794b29b88a3a2a82cf524080b551b81b67f143fefc2970310fb6c8",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "com.microsoft.product": "Microsoft SQL Server",
                "com.microsoft.version": "14.0.3048.4",
                "vendor": "Microsoft"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1353110161,
        "VirtualSize": 1353110161,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/08196c17518227a63394f8edbfba8772e50e38f1212327d71a4ba880d031b261/diff:/var/lib/docker/overlay2/cac1716072ca4175d6f117b13c08d3106b3b3502ec1c741e2af6cb100ff2c992/diff:/var/lib/docker/overlay2/3360cfdce7995cd50bf3f0245cef1c6ac3bd915b5f14abb9bed9112e23d5fafc/diff:/var/lib/docker/overlay2/c60606cc74efc4ee86a77b7e218a14c1d7ae4d6fbb90ea2be5d416d9246a108c/diff:/var/lib/docker/overlay2/e0b6b3716b86d38f72bde18537f611cab9b6105bf06be59fb879a93ad377486a/diff:/var/lib/docker/overlay2/13edd7fb69258dc38599901040727c1ee0fc8139613179422c11fd02f7d518b3/diff:/var/lib/docker/overlay2/73abb0ed3e4393f13982a4159a4fe458a695e6fede891a079f0f9162f4b2e6ab/diff:/var/lib/docker/overlay2/9933000f6efd6cbf4a8458c5fe7b235a435d4c5a7777c242322d3fac76d24065/diff",
                "MergedDir": "/var/lib/docker/overlay2/478e285b250a718ee8ecd31027c99abfe85aece8de68035dee35c4175797e24a/merged",
                "UpperDir": "/var/lib/docker/overlay2/478e285b250a718ee8ecd31027c99abfe85aece8de68035dee35c4175797e24a/diff",
                "WorkDir": "/var/lib/docker/overlay2/478e285b250a718ee8ecd31027c99abfe85aece8de68035dee35c4175797e24a/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:644879075e24394efef8a7dddefbc133aad42002df6223cacf98bd1e3d5ddde2",
                "sha256:d7ff1dc646ba52a02312b535446d6c9b72cd09fda0480524e4828554efb2f748",
                "sha256:686245e78935e73b737c9a82111c3c7df35f5529d06ce8c2f9a7cd32ec90b456",
                "sha256:d73dd9e652956dccbbef716de4b172cc15fff644cc92fc69d221cc3a1cb89a39",
                "sha256:2de391e51d731ba02b708038a7f98b7103061b916727bcd165e9ee6402f4cdde",
                "sha256:d33a8ef9dea5016c8647174b5580425f021385b9ab87453cd7508587c030305c",
                "sha256:911ad08015cfe167b552e1c330220f90e4ff82f572bfb309f7e3afab619d71fc",
                "sha256:be08dc7c21612388e812298a006b9fd65095b985de77c71d62f20008945997a6",
                "sha256:79b07b78f674ac90913b63152a2cf7060d363552b6174cc966bd841569b7fb95"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

**Comment by EdwinVW** [comment] 2019-01-17 08:43
Thanks for the update! 

I've ran a test this morning in which I completely removed all the databases from SQL Server and started the solution using `docker-compose up`. All the databases (including the _WorkshopManagementEventStore_ were created successfully and everything worked fine. So I cannot reproduce the error.

I notice you have a newer version of SQL Server (you run `14.0.3048.4` and I have `14.0.3038.14`). I will try to upgrade later today to check whether this has anything to do with the error (although I don't expect this to be the issue).

I haven't worked with Kitematic before, so I don't know whether or not this has anything to do with the error. The Docker documentation states that you should replace Kitematic with Docker Desktop for Mac or Windows (see [https://docs.docker.com/kitematic/](https://docs.docker.com/kitematic/)). So I would suggest that you try to install Docker Desktop, follow the instructions on RAM configuration and try again. Is that something you can do?

**Comment by EdwinVW** [comment] 2019-01-17 22:40
Hi @wensan312, I have an update. I have pulled the latest version of the SQL Server docker image (I also run `14.0.3048.4` now) and did another test where I removed all databases and started the application. Everything worked fine and all databases were created. So the difference in SQL Server version is not the cause.

**Comment by wensan312** [comment] 2019-01-18 00:03
Thank you for you hard work! May I know how do you create those database. I need to double check why is the specific database is not created.

**Comment by EdwinVW** [comment] 2019-01-20 21:06
The database is created in the constructor of the `SqlServerWorkshopPlanningRepository`. See [SqlServerWorkshopPlanningRepository.cs](https://github.com/EdwinVW/pitstop/blob/master/src/WorkshopManagementAPI/Repositories/SqlServerWorkshopPlanningRepository.cs).

**Comment by EdwinVW** [comment] 2019-01-23 11:13
Hi @wensan312, I've been able to reproduce the error! I reset my Docker desktop to factory defaults, pulled all new images from Docker Hub and rebuilt all the Pitstop docker images. 

The error occurred the first time I accessed the _Workshop Management_ tab in the web-application. I saw in SSMS that database was created successfully. After I refreshed the page (by clicking on the tab again) it worked fine. 

I expect it has something to do with the switch from the _master_ database to the _WorkshopManagementEventStore_ database after it is created (this is in the repo code). I will look into this and let you know asap what the root-cause is!

**Comment by EdwinVW** [comment] 2019-01-23 14:23
Hi @wensan312. I've updated the DB initialization code (6f071b2456399fc30ef161f6f65e873d0832ffd3). This fixed the issue for me (when starting from scratch). Can you pull the latest version and check whether or not the issue is fixed?

**Comment by EdwinVW** [comment] 2019-01-29 05:59
Hi @wensan312, did you have the chance to try the latest version and see whether or not the issue is fixed?

**Comment by EdwinVW** [comment] 2019-03-17 10:53
Hello @wensan312. Do you have any updates?

**Comment by EdwinVW** [comment] 2019-03-25 20:19
I will close the issue for now. If you have any question or issue later, please open a new issue and reference this one.

**Closed by EdwinVW** 2019-03-25 20:19 UTC
Labels: fix available, reproducible, under investigation
